# Generated by Django 5.0 on 2023-12-14 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictation", "0004_rename_dictation_practice_dictation_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="practice",
            old_name="dictation_id",
            new_name="dictation",
        ),
    ]
