# Generated by Django 5.0 on 2023-12-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictation", "0005_rename_dictation_id_practice_dictation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="dictation",
            field=models.ForeignKey(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id",
                to="dictation.dictation",
            ),
        ),
    ]
