# Generated by Django 5.0 on 2023-12-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictation", "0006_alter_practice_dictation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictation",
            name="total_line",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="practice",
            name="dictation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dictation.dictation"
            ),
        ),
    ]
