# Generated by Django 5.0 on 2023-12-20 13:59

import apps.dictation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictation", "0007_dictation_total_line_alter_practice_dictation"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="lines",
            field=models.JSONField(default=apps.dictation.models.lines_default),
        ),
    ]
