# Generated by Django 5.0 on 2023-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0008_practice_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
    ]
