# Generated by Django 5.0 on 2023-12-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictation_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
